#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Jul 21 11:45:24 +0200 2022
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm ad_converter_serial_receiver_v1_00_a axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_21 lib_pkg_v1_0_2 axi_timer_v2_0_21 bidir_io_port_v1_00_a da_converter_interface_v1_00_a incremental_encoder_interface_v1_00_a axi_infrastructure_v1_1_0 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 register_array_v1_00_a proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 xlslice_v1_0_2 xlconcat_v2_1_3 xlconstant_v1_1_6 filter_block_v1_00_a driver_interface_v1_00_a xbip_utils_v3_0_10 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_13 switching_event_counter_v1_00_a util_reduced_logic_v2_0_4 comparator_limiter_block_v1_00_a pulse_width_modulator_v1_00_a xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_13 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 xbip_bram18k_v3_0_6 mult_gen_v12_0_15 axi_protocol_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work ad_converter_serial_receiver_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/59e0/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/59e0/hdl/vhdl/ad_converter_serial_receiver_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ad_converter_0/sim/design_1_ad_converter_0.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/5850/hdl/array_resize.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_array_resize_0_0/sim/design_1_array_resize_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_array_resize_1_0/sim/design_1_array_resize_1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_array_resize_2_0/sim/design_1_array_resize_2_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_array_resize_3_0/sim/design_1_array_resize_3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_0/sim/design_1_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_2_0/sim/design_1_axi_gpio_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/a788/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_0/sim/design_1_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work bidir_io_port_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/c52a/hdl/vhdl/bidir_io_port.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_bidir_io_port_0_0/sim/design_1_bidir_io_port_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work da_converter_interface_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/251e/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/251e/hdl/vhdl/da_converter_interface_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_da_converter_0/sim/design_1_da_converter_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work incremental_encoder_interface_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/c80b/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/c80b/hdl/vhdl/incremental_encoder_interface_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_encoder_interface_0/sim/design_1_encoder_interface_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work register_array_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ac34/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ac34/hdl/vhdl/register_array_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_relay_0/sim/design_1_relay_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_in_0/sim/design_1_signal_in_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_signalinverter_0/sim/design_1_signalinverter_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_testled_0/sim/design_1_testled_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_1_0/sim/design_1_util_vector_logic_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_interrupt_control.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_axi_xadc.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xadcmuxslice_0/sim/design_1_xadcmuxslice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_1_0/sim/design_1_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_2_0/sim/design_1_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_4_0/sim/design_1_xlconstant_4_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_irq_xlconcat_0_1/sim/design_1_irq_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_1_1/sim/design_1_xlconcat_1_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_1_2/sim/design_1_xlconcat_1_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_4_1/sim/design_1_xlconcat_4_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_5_1/sim/design_1_xlconcat_5_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_6_1/sim/design_1_xlconcat_6_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work filter_block_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/a6f3/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/a6f3/hdl/vhdl/filter_block_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AD_filter_block_1/sim/design_1_AD_filter_block_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work driver_interface_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/3f13/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/3f13/hdl/vhdl/driver_interface_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_driver_interface_0/sim/design_1_driver_interface_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_synch_sampling_reg_1/sim/design_1_synch_sampling_reg_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_1/sim/design_1_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_CurrentRef_0/sim/design_1_CurrentRef_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_2_2/sim/design_1_xlconcat_2_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/cd8a/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_synch_sampling_latch_1/sim/design_1_synch_sampling_latch_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work switching_event_counter_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/27ad/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/27ad/hdl/vhdl/switching_event_counter_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_switching_event_counter_0/sim/design_1_switching_event_counter_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_3_1/sim/design_1_xlconcat_3_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/abe2/hdl/vhdl/signal_operasjon_blokk.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_1_1/sim/design_1_signal_operasjon_blokk_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_4_2/sim/design_1_xlconcat_4_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_5_2/sim/design_1_xlconcat_5_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_2_1/sim/design_1_signal_operasjon_blokk_2_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_accumulator_1/sim/design_1_accumulator_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_moving_integral_reg_1/sim/design_1_moving_integral_reg_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_6_2/sim/design_1_xlconcat_6_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_3_1/sim/design_1_signal_operasjon_blokk_3_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_reduced_logic_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_reduced_logic_0_1/sim/design_1_util_reduced_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work comparator_limiter_block_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/b48c/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/b48c/hdl/vhdl/comparator_limiter_block_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Hysteresis_control_0/sim/design_1_Hysteresis_control_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_6_1/sim/design_1_xlconstant_6_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_7_1/sim/design_1_xlconcat_7_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work pulse_width_modulator_v1_00_a $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/c07a/hdl/vhdl/user_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/c07a/hdl/vhdl/pulse_width_modulator_axi.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_pwm_0/sim/design_1_pwm_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_moving_integral_latch_2/sim/design_1_moving_integral_latch_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_3_2/sim/design_1_xlconstant_3_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_5_2/sim/design_1_xlconstant_5_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/sim/blankingtimecorr_c_counter_binary_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i1/sim/blankingtimecorr_c_counter_binary_v12_0_i1.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/srl17e.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/srl33e.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/blankingtimecorr_entity_declarations.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/blankingtimecorr.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/blankingtimecorr_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/synth_reg.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl/convert_type.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blankingtimecorr_0_2/sim/design_1_blankingtimecorr_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_2/sim/design_1_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Hysteresis_control_1/sim/design_1_Hysteresis_control_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_2_4/sim/design_1_xlconcat_2_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_reduced_logic_0_2/sim/design_1_util_reduced_logic_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_1/sim/design_1_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_AD_filter_block_2/sim/design_1_AD_filter_block_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_driver_interface_1/sim/design_1_driver_interface_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_synch_sampling_reg_2/sim/design_1_synch_sampling_reg_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_4/sim/design_1_util_vector_logic_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_CurrentRef_1/sim/design_1_CurrentRef_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_2_5/sim/design_1_xlconcat_2_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_synch_sampling_latch_2/sim/design_1_synch_sampling_latch_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_switching_event_counter_1/sim/design_1_switching_event_counter_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_3_2/sim/design_1_xlconcat_3_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_1_2/sim/design_1_signal_operasjon_blokk_1_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_4_3/sim/design_1_xlconcat_4_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_5_3/sim/design_1_xlconcat_5_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_2_2/sim/design_1_signal_operasjon_blokk_2_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Moving_integral_0/sim/design_1_Moving_integral_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_moving_integral_reg_2/sim/design_1_moving_integral_reg_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_6_3/sim/design_1_xlconcat_6_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_signal_operasjon_blokk_3_2/sim/design_1_signal_operasjon_blokk_3_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_reduced_logic_0_3/sim/design_1_util_reduced_logic_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Hysteresis_control_2/sim/design_1_Hysteresis_control_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_6_2/sim/design_1_xlconstant_6_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_7_2/sim/design_1_xlconcat_7_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_pwm_1/sim/design_1_pwm_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_moving_integral_latch_0/sim/design_1_moving_integral_latch_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_3_0/sim/design_1_xlconstant_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_5_0/sim/design_1_xlconstant_5_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blankingtimecorr_0_0/sim/design_1_blankingtimecorr_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_1_1/sim/design_1_util_vector_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_Tripping_0/sim/design_1_Tripping_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_8_0/sim/design_1_xlconcat_8_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_reduced_logic_1_0/sim/design_1_util_reduced_logic_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_2/sim/design_1_xlslice_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_1_0/sim/design_1_xlslice_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_1_1/sim/design_1_xlconstant_1_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_6_3/sim/design_1_xlconstant_6_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_6_0/sim/design_1_xlconstant_6_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_1/sim/design_1_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_5_3/sim/design_1_xlconstant_5_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_3/sim/design_1_xlslice_0_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_2_2/sim/design_1_xlslice_2_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_3_0/sim/design_1_xlslice_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_2_3/sim/design_1_xlslice_2_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_3_1/sim/design_1_xlslice_3_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_4_0/sim/design_1_xlslice_4_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_7_1/sim/design_1_xlconstant_7_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_3/sim/design_1_xlconcat_0_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_2_4/sim/design_1_xlslice_2_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_3_2/sim/design_1_xlslice_3_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_8_1/sim/design_1_xlconcat_8_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_3_3/sim/design_1_xlslice_3_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_4_1/sim/design_1_xlslice_4_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_9_1/sim/design_1_xlconcat_9_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/b429/src/multiplexer.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/b429/hdl/multiplexer_v1_0_S_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/b429/hdl/multiplexer_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_multiplexer_0_0/sim/design_1_multiplexer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_5_4/sim/design_1_xlconstant_5_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_register_array_0_0/sim/design_1_register_array_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_register_array_1_0/sim/design_1_register_array_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_3_3/sim/design_1_xlconcat_3_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_register_emu_out_0/sim/design_1_register_emu_out_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_8_2/sim/design_1_xlconcat_8_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_c_shift_ram_0_0/sim/design_1_c_shift_ram_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_c_shift_ram_1_0/sim/design_1_c_shift_ram_1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_c_shift_ram_2_0/sim/design_1_c_shift_ram_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_2_5/sim/design_1_xlslice_2_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_array_resize_3_1/sim/design_1_array_resize_3_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_5_4/sim/design_1_xlconcat_5_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_7/sim/design_1_util_vector_logic_0_7.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_11_0/sim/design_1_xlconcat_11_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i0/sim/emu_dc_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i1/sim/emu_dc_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i2/sim/emu_dc_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i3/sim/emu_dc_c_addsub_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_counter_binary_v12_0_i0/sim/emu_dc_c_counter_binary_v12_0_i0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i0/sim/emu_dc_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i1/sim/emu_dc_mult_gen_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i2/sim/emu_dc_mult_gen_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i3/sim/emu_dc_mult_gen_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i4/sim/emu_dc_mult_gen_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i5/sim/emu_dc_mult_gen_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i6/sim/emu_dc_mult_gen_v12_0_i6.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/srl17e.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/srl33e.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc_entity_declarations.vhd" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/emu_dc_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl/convert_type.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_emu_dc_0_1/sim/design_1_emu_dc_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_0_0/sim/design_1_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_1_0/sim/design_1_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_2_0/sim/design_1_tier2_xbar_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_3_0/sim/design_1_tier2_xbar_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_4_0/sim/design_1_tier2_xbar_4_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/58cf/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ipshared/8936/hdl" +incdir+"$ref_dir/../../../../L2_Ph3_L2_Ph3_DC_Drive.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
