# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraints/PicoZed7030_prosessorkort_IO.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ad_converter_0/design_1_ad_converter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ad_converter_0 || ORIG_REF_NAME==design_1_ad_converter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_array_resize_0_0/design_1_array_resize_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_array_resize_0_0 || ORIG_REF_NAME==design_1_array_resize_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_array_resize_1_0/design_1_array_resize_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_array_resize_1_0 || ORIG_REF_NAME==design_1_array_resize_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_array_resize_2_0/design_1_array_resize_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_array_resize_2_0 || ORIG_REF_NAME==design_1_array_resize_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_array_resize_3_0/design_1_array_resize_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_array_resize_3_0 || ORIG_REF_NAME==design_1_array_resize_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bidir_io_port_0_0/design_1_bidir_io_port_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bidir_io_port_0_0 || ORIG_REF_NAME==design_1_bidir_io_port_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_da_converter_0/design_1_da_converter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_da_converter_0 || ORIG_REF_NAME==design_1_da_converter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_encoder_interface_0/design_1_encoder_interface_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_interface_0 || ORIG_REF_NAME==design_1_encoder_interface_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_relay_0/design_1_relay_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_relay_0 || ORIG_REF_NAME==design_1_relay_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_in_0/design_1_signal_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_in_0 || ORIG_REF_NAME==design_1_signal_in_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signalinverter_0/design_1_signalinverter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signalinverter_0 || ORIG_REF_NAME==design_1_signalinverter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_testled_0/design_1_testled_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_testled_0 || ORIG_REF_NAME==design_1_testled_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadcmuxslice_0/design_1_xadcmuxslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadcmuxslice_0 || ORIG_REF_NAME==design_1_xadcmuxslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_0/design_1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_0 || ORIG_REF_NAME==design_1_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0/design_1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_4_0/design_1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_4_0 || ORIG_REF_NAME==design_1_xlconstant_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_irq_xlconcat_0_1/design_1_irq_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_irq_xlconcat_0_1 || ORIG_REF_NAME==design_1_irq_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_1/design_1_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_1 || ORIG_REF_NAME==design_1_xlconcat_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_2/design_1_xlconcat_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_2 || ORIG_REF_NAME==design_1_xlconcat_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_4_1/design_1_xlconcat_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_4_1 || ORIG_REF_NAME==design_1_xlconcat_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_5_1/design_1_xlconcat_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_5_1 || ORIG_REF_NAME==design_1_xlconcat_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_6_1/design_1_xlconcat_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_6_1 || ORIG_REF_NAME==design_1_xlconcat_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AD_filter_block_1/design_1_AD_filter_block_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AD_filter_block_1 || ORIG_REF_NAME==design_1_AD_filter_block_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_driver_interface_0/design_1_driver_interface_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_driver_interface_0 || ORIG_REF_NAME==design_1_driver_interface_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_synch_sampling_reg_1/design_1_synch_sampling_reg_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_synch_sampling_reg_1 || ORIG_REF_NAME==design_1_synch_sampling_reg_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CurrentRef_0/design_1_CurrentRef_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CurrentRef_0 || ORIG_REF_NAME==design_1_CurrentRef_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_2_2/design_1_xlconcat_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_2_2 || ORIG_REF_NAME==design_1_xlconcat_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_synch_sampling_latch_1/design_1_synch_sampling_latch_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_synch_sampling_latch_1 || ORIG_REF_NAME==design_1_synch_sampling_latch_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_switching_event_counter_0/design_1_switching_event_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_switching_event_counter_0 || ORIG_REF_NAME==design_1_switching_event_counter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_1/design_1_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_1 || ORIG_REF_NAME==design_1_xlconcat_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_1_1/design_1_signal_operasjon_blokk_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_1_1 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_4_2/design_1_xlconcat_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_4_2 || ORIG_REF_NAME==design_1_xlconcat_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_5_2/design_1_xlconcat_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_5_2 || ORIG_REF_NAME==design_1_xlconcat_5_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_2_1/design_1_signal_operasjon_blokk_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_2_1 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_accumulator_1/design_1_accumulator_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_accumulator_1 || ORIG_REF_NAME==design_1_accumulator_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_integral_reg_1/design_1_moving_integral_reg_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_moving_integral_reg_1 || ORIG_REF_NAME==design_1_moving_integral_reg_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_6_2/design_1_xlconcat_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_6_2 || ORIG_REF_NAME==design_1_xlconcat_6_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_3_1/design_1_signal_operasjon_blokk_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_3_1 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_1/design_1_util_reduced_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_1 || ORIG_REF_NAME==design_1_util_reduced_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Hysteresis_control_0/design_1_Hysteresis_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Hysteresis_control_0 || ORIG_REF_NAME==design_1_Hysteresis_control_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_1/design_1_xlconstant_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_1 || ORIG_REF_NAME==design_1_xlconstant_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_7_1/design_1_xlconcat_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_7_1 || ORIG_REF_NAME==design_1_xlconcat_7_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwm_0/design_1_pwm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_0 || ORIG_REF_NAME==design_1_pwm_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_integral_latch_2/design_1_moving_integral_latch_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_moving_integral_latch_2 || ORIG_REF_NAME==design_1_moving_integral_latch_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_2/design_1_xlconstant_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_2 || ORIG_REF_NAME==design_1_xlconstant_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_5_2/design_1_xlconstant_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_5_2 || ORIG_REF_NAME==design_1_xlconstant_5_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_2/design_1_blankingtimecorr_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blankingtimecorr_0_2 || ORIG_REF_NAME==design_1_blankingtimecorr_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i0/blankingtimecorr_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_2/blankingtimecorr_c_counter_binary_v12_0_i1/blankingtimecorr_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_2/design_1_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_2 || ORIG_REF_NAME==design_1_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Hysteresis_control_1/design_1_Hysteresis_control_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Hysteresis_control_1 || ORIG_REF_NAME==design_1_Hysteresis_control_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_2_4/design_1_xlconcat_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_2_4 || ORIG_REF_NAME==design_1_xlconcat_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_2/design_1_util_reduced_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_2 || ORIG_REF_NAME==design_1_util_reduced_logic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AD_filter_block_2/design_1_AD_filter_block_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AD_filter_block_2 || ORIG_REF_NAME==design_1_AD_filter_block_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_driver_interface_1/design_1_driver_interface_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_driver_interface_1 || ORIG_REF_NAME==design_1_driver_interface_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_synch_sampling_reg_2/design_1_synch_sampling_reg_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_synch_sampling_reg_2 || ORIG_REF_NAME==design_1_synch_sampling_reg_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_4/design_1_util_vector_logic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_4 || ORIG_REF_NAME==design_1_util_vector_logic_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CurrentRef_1/design_1_CurrentRef_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CurrentRef_1 || ORIG_REF_NAME==design_1_CurrentRef_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_2_5/design_1_xlconcat_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_2_5 || ORIG_REF_NAME==design_1_xlconcat_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_synch_sampling_latch_2/design_1_synch_sampling_latch_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_synch_sampling_latch_2 || ORIG_REF_NAME==design_1_synch_sampling_latch_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_switching_event_counter_1/design_1_switching_event_counter_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_switching_event_counter_1 || ORIG_REF_NAME==design_1_switching_event_counter_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_2/design_1_xlconcat_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_2 || ORIG_REF_NAME==design_1_xlconcat_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_1_2/design_1_signal_operasjon_blokk_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_1_2 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_4_3/design_1_xlconcat_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_4_3 || ORIG_REF_NAME==design_1_xlconcat_4_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_5_3/design_1_xlconcat_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_5_3 || ORIG_REF_NAME==design_1_xlconcat_5_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_2_2/design_1_signal_operasjon_blokk_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_2_2 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Moving_integral_0/design_1_Moving_integral_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Moving_integral_0 || ORIG_REF_NAME==design_1_Moving_integral_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_integral_reg_2/design_1_moving_integral_reg_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_moving_integral_reg_2 || ORIG_REF_NAME==design_1_moving_integral_reg_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_6_3/design_1_xlconcat_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_6_3 || ORIG_REF_NAME==design_1_xlconcat_6_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signal_operasjon_blokk_3_2/design_1_signal_operasjon_blokk_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_signal_operasjon_blokk_3_2 || ORIG_REF_NAME==design_1_signal_operasjon_blokk_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_3/design_1_util_reduced_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_3 || ORIG_REF_NAME==design_1_util_reduced_logic_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Hysteresis_control_2/design_1_Hysteresis_control_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Hysteresis_control_2 || ORIG_REF_NAME==design_1_Hysteresis_control_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_2/design_1_xlconstant_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_2 || ORIG_REF_NAME==design_1_xlconstant_6_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_7_2/design_1_xlconcat_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_7_2 || ORIG_REF_NAME==design_1_xlconcat_7_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwm_1/design_1_pwm_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_1 || ORIG_REF_NAME==design_1_pwm_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_integral_latch_0/design_1_moving_integral_latch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_moving_integral_latch_0 || ORIG_REF_NAME==design_1_moving_integral_latch_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_0/design_1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_0 || ORIG_REF_NAME==design_1_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_5_0/design_1_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_5_0 || ORIG_REF_NAME==design_1_xlconstant_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_0/design_1_blankingtimecorr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blankingtimecorr_0_0 || ORIG_REF_NAME==design_1_blankingtimecorr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_0/blankingtimecorr_c_counter_binary_v12_0_i0/blankingtimecorr_c_counter_binary_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blankingtimecorr_0_0/blankingtimecorr_c_counter_binary_v12_0_i1/blankingtimecorr_c_counter_binary_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==blankingtimecorr_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_1/design_1_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_1 || ORIG_REF_NAME==design_1_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Tripping_0/design_1_Tripping_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Tripping_0 || ORIG_REF_NAME==design_1_Tripping_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_8_0/design_1_xlconcat_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_8_0 || ORIG_REF_NAME==design_1_xlconcat_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_1_0/design_1_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_1_0 || ORIG_REF_NAME==design_1_util_reduced_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_1/design_1_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_1 || ORIG_REF_NAME==design_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_3/design_1_xlconstant_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_3 || ORIG_REF_NAME==design_1_xlconstant_6_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_0/design_1_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_0 || ORIG_REF_NAME==design_1_xlconstant_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_5_3/design_1_xlconstant_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_5_3 || ORIG_REF_NAME==design_1_xlconstant_5_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_3/design_1_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_3 || ORIG_REF_NAME==design_1_xlslice_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_2/design_1_xlslice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_2 || ORIG_REF_NAME==design_1_xlslice_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_3/design_1_xlslice_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_3 || ORIG_REF_NAME==design_1_xlslice_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_1/design_1_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_1 || ORIG_REF_NAME==design_1_xlslice_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_7_1/design_1_xlconstant_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_7_1 || ORIG_REF_NAME==design_1_xlconstant_7_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_3/design_1_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_3 || ORIG_REF_NAME==design_1_xlconcat_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_4/design_1_xlslice_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_4 || ORIG_REF_NAME==design_1_xlslice_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_2/design_1_xlslice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_2 || ORIG_REF_NAME==design_1_xlslice_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_8_1/design_1_xlconcat_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_8_1 || ORIG_REF_NAME==design_1_xlconcat_8_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_3/design_1_xlslice_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_3 || ORIG_REF_NAME==design_1_xlslice_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_4_1/design_1_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_1 || ORIG_REF_NAME==design_1_xlslice_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_9_1/design_1_xlconcat_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_9_1 || ORIG_REF_NAME==design_1_xlconcat_9_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_multiplexer_0_0/design_1_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_multiplexer_0_0 || ORIG_REF_NAME==design_1_multiplexer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_5_4/design_1_xlconstant_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_5_4 || ORIG_REF_NAME==design_1_xlconstant_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_array_0_0/design_1_register_array_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_register_array_0_0 || ORIG_REF_NAME==design_1_register_array_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_array_1_0/design_1_register_array_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_register_array_1_0 || ORIG_REF_NAME==design_1_register_array_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_3/design_1_xlconcat_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_3 || ORIG_REF_NAME==design_1_xlconcat_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_emu_out_0/design_1_register_emu_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_register_emu_out_0 || ORIG_REF_NAME==design_1_register_emu_out_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_8_2/design_1_xlconcat_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_8_2 || ORIG_REF_NAME==design_1_xlconcat_8_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_0_0/design_1_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_0 || ORIG_REF_NAME==design_1_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_1_0/design_1_c_shift_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_1_0 || ORIG_REF_NAME==design_1_c_shift_ram_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_2_0/design_1_c_shift_ram_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_2_0 || ORIG_REF_NAME==design_1_c_shift_ram_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_5/design_1_xlslice_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_5 || ORIG_REF_NAME==design_1_xlslice_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_array_resize_3_1/design_1_array_resize_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_array_resize_3_1 || ORIG_REF_NAME==design_1_array_resize_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_5_4/design_1_xlconcat_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_5_4 || ORIG_REF_NAME==design_1_xlconcat_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_7/design_1_util_vector_logic_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_7 || ORIG_REF_NAME==design_1_util_vector_logic_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_11_0/design_1_xlconcat_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_11_0 || ORIG_REF_NAME==design_1_xlconcat_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/design_1_emu_dc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_emu_dc_0_1 || ORIG_REF_NAME==design_1_emu_dc_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i0/emu_dc_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_c_addsub_v12_0_i0 || ORIG_REF_NAME==emu_dc_c_addsub_v12_0_i0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i1/emu_dc_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_c_addsub_v12_0_i1 || ORIG_REF_NAME==emu_dc_c_addsub_v12_0_i1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i2/emu_dc_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_c_addsub_v12_0_i2 || ORIG_REF_NAME==emu_dc_c_addsub_v12_0_i2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_addsub_v12_0_i3/emu_dc_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_c_addsub_v12_0_i3 || ORIG_REF_NAME==emu_dc_c_addsub_v12_0_i3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_c_counter_binary_v12_0_i0/emu_dc_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==emu_dc_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i0/emu_dc_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i0 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i1/emu_dc_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i1 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i2/emu_dc_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i2 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i3/emu_dc_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i3 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i4/emu_dc_mult_gen_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i4 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i5/emu_dc_mult_gen_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i5 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emu_dc_0_1/emu_dc_mult_gen_v12_0_i6/emu_dc_mult_gen_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emu_dc_mult_gen_v12_0_i6 || ORIG_REF_NAME==emu_dc_mult_gen_v12_0_i6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ENDAT22_S_0_0/design_1_ENDAT22_S_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ENDAT22_S_0_0 || ORIG_REF_NAME==design_1_ENDAT22_S_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_apb_bridge_0_0/design_1_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_apb_bridge_0_0 || ORIG_REF_NAME==design_1_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_4/design_1_xlconstant_6_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_4 || ORIG_REF_NAME==design_1_xlconstant_6_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_3_0/design_1_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_3_0 || ORIG_REF_NAME==design_1_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_4_0/design_1_tier2_xbar_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_4_0 || ORIG_REF_NAME==design_1_tier2_xbar_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_signal_in_0/design_1_signal_in_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_signal_in_0 || ORIG_REF_NAME==design_1_signal_in_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_signal_in_0/design_1_signal_in_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_signal_in_0/design_1_signal_in_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_signal_in_0 || ORIG_REF_NAME==design_1_signal_in_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_testled_0/design_1_testled_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_testled_0 || ORIG_REF_NAME==design_1_testled_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_testled_0/design_1_testled_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_testled_0/design_1_testled_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_testled_0 || ORIG_REF_NAME==design_1_testled_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_blankingtimecorr_0_2/constrs/blankingtimecorr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_blankingtimecorr_0_2 || ORIG_REF_NAME==design_1_blankingtimecorr_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_blankingtimecorr_0_0/constrs/blankingtimecorr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_blankingtimecorr_0_0 || ORIG_REF_NAME==design_1_blankingtimecorr_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_emu_dc_0_1/constrs/emu_dc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_emu_dc_0_1 || ORIG_REF_NAME==design_1_emu_dc_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_ENDAT22_S_0_0/src/endat22/constraints.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ENDAT22_S_0_0 || ORIG_REF_NAME==design_1_ENDAT22_S_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_apb_bridge_0_0/design_1_axi_apb_bridge_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_tier2_xbar_3_0/design_1_tier2_xbar_3_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_tier2_xbar_4_0/design_1_tier2_xbar_4_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
